#pragma once
#include <3ds.h>
#include <citro2d.h>
#include <string>
#include <vector>
#include <map>

struct V2File {
    std::string name;   // filename only (e.g. "Zelda-Overworld.v2m")
    std::string path;   // full SD path
    std::string group;  // subfolder name, or "" if in the root maps folder
};

// Loaded from a .pos sidecar file generated by the companion calibration tool.
// Tells drawMap how to convert a NES RAM screen-index value into a pixel
// position on the overworld image so it can draw a "you are here" dot.
struct PosCalibration {
    bool  valid      = false;
    int   ramAddr    = 0;      // NES RAM address to read (decimal), e.g. 0xEB=235 for Zelda
    int   worldCols  = 1;      // grid width in screens (e.g. 16 for Zelda)
    int   worldRows  = 1;      // grid height in screens (e.g. 8 for Zelda)
    float mapLeft    = 0.0f;   // normalized image coords of the grid boundary
    float mapTop     = 0.0f;
    float mapRight   = 1.0f;
    float mapBottom  = 1.0f;
};

struct V2Tile {
    C3D_Tex tex;
    C2D_Image image;
    Tex3DS_SubTexture subTex;
    u32 width;
    u32 height;
    bool isRGBA8;
};

class V2Content {
public:
    V2Content();
    ~V2Content();

    void scanFiles();
    // Returns the unique group names (subfolders) present in a file list,
    // preserving the order they were first encountered. Files with no group
    // are collected under the special name "Other".
    static std::vector<std::string> getGroups(const std::vector<V2File>& files);
    
    std::vector<V2File> mapFiles;
    std::vector<V2File> walkFiles;
    std::vector<V2File> romFiles;

    // Map Viewing
    bool loadMap(const char* path);
    void freeMap();
    // Pre-load every map file whose name starts with `prefix` into the cache.
    // Subsequent loadMap calls for those paths are instant (no SD read, no swizzle).
    void preloadMatchingMaps(const std::string& prefix);
    bool loadNextMap(const std::string& prefix, size_t& cursor);
    // Release every cached map and free their GPU textures. Call when switching games.
    void freeAllCachedMaps();
    // Free all cached maps except the one at the given path (keeps active map alive).
    void freeAllCachedMapsExcept(const std::string& keepPath);
    // Free all cached maps except two paths (overworld + current dungeon).
    void freeAllCachedMapsExcept(const std::string& keep1, const std::string& keep2);
    // Free a single map from the cache (GPU texture + memory). Used by auto-switcher
    // to reclaim VRAM when moving between levels that won't be revisited soon.
    void freeMapFromCache(const std::string& path);

    // Path of the overworld map for this game — always kept in cache while playing.
    std::string overworldMapPath;
    // Calibration data loaded from a .pos sidecar file (same name as the .v2m,
    // .pos extension). Automatically populated by loadPosCalib() whenever a map
    // is activated. If no sidecar exists, posCalib.valid stays false.
    PosCalibration posCalib;
    // Load calibration from the .pos sidecar file beside the given map path.
    // Resets posCalib.valid = false if the file does not exist or is malformed.
    void loadPosCalib(const std::string& mapPath);
    // playerRamVal: the current value read from the RAM address in posCalib.
    // Pass -1 (default) to suppress the marker.
    void drawMap(float viewportH = 240.0f, int playerRamVal = -1);
    void zoomIn(float factor = 1.25f, float viewportH = 240.0f);
    void zoomOut(float factor = 1.25f, float viewportH = 240.0f);
    void pan(float dx, float dy, float viewportH = 240.0f);
    void resetView(float viewportH = 240.0f);
    std::string currentMapPath;
    void saveMapView();
    bool loadMapView();
    void saveMapBookmark();
    std::string loadMapBookmark();

    // Walkthrough Viewing
    bool loadWalk(const char* path);
    std::string currentWalkPath;
    void saveWalkPosition(int currentScroll);
    int loadWalkPosition();
    void freeWalk();
    void drawWalk(int scrollY);
    int getWalkHeight();

    // Preload a map by path (caches it without activating). Used to prioritize
    // the active map's GPU memory allocation before other maps.
    bool preloadMap(const std::string& path);

    // Bookmark
    void saveBookmark();
    std::string loadBookmark();



private:
    // Texture for the map
    C3D_Tex mapTex;
    C2D_Image mapImage;
    Tex3DS_SubTexture mapSubTex;
    bool mapLoaded = false;
    float mapAspect = 1.0f;
    u32 targetW = 1024;
    u32 targetH = 1024;

    std::vector<V2Tile*> mapTiles;
    u32 gridCols = 1;
    u32 gridRows = 1;
    u32 originalWidth = 1024;
    u32 originalHeight = 1024;

    // Cached maps for instant switching. Each entry owns its V2Tile* pointers
    // (the GPU textures stay alive until freeAllCachedMaps is called).
    struct CachedMap {
        std::vector<V2Tile*> tiles;
        u32 gridCols = 1, gridRows = 1;
        u32 originalWidth = 1024, originalHeight = 1024;
        float aspect = 1.0f;
    };
    std::map<std::string, CachedMap> mapCache;

    // Internal: load a map from disk and put it in the cache. Returns true on success.
    // Does NOT change the active map.
    bool cacheMapFromDisk(const std::string& path);
    // Internal: point the active-map members at a cached entry.
    void activateCachedMap(const std::string& path);

    // Zoom and Pan state
    float zoom = 1.0f;
    float panX = 0.0f;
    float panY = -40.0f;

    // Walkthrough line storage
    std::vector<std::string> walkLines;
    std::vector<int> walkLineYOffsets;
    int walkTotalHeight = 0;
    bool walkLoaded = false;
};

